on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_TOKEN}}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.PUBLIC_IP}} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ubuntu@${{ secrets.PUBLIC_IP }} "cd /home/ubuntu/ && git checkout main && /home/ubuntu/deploy.sh"
    - name: cleanup
      run: rm -rf ~/.ssh/id_rsa